apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: pod-status-check
  namespace: kuberhealthy
spec:
  runInterval: 2m
  timeout: 1m
  podSpec:
    containers:
      - env:
          - name: REPORT_FAILURE
            value: "false"
          - name: REPORT_DELAY
            value: "5s"
        image: quay.io/comcast/pod-status-check:1.0.0
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
